import * as Dialog from "@radix-ui/react-dialog";
import { cva, type VariantProps } from "class-variance-authority";
import { twMerge } from "tailwind-merge";
import { clsx, type ClassValue } from "clsx";
import { X } from "lucide-react";
import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode } from "react";

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
const button = cva("inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-4 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-700 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50", { variants: { variant: { primary: "bg-slate-900 text-white hover:bg-slate-800", secondary: "border border-slate-300 bg-white text-slate-900 hover:bg-slate-50", ghost: "text-slate-700 hover:bg-slate-100", danger: "border border-red-200 bg-red-50 text-red-700" } }, defaultVariants: { variant: "primary" } });
export function Button({ className, variant, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof button>) { return <button className={cn(button({ variant }), className)} {...props} />; }
export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-[10px] border border-slate-200 bg-white", className)} {...props} />; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "green" | "amber" | "blue" }) { const styles = { neutral: "bg-slate-100 text-slate-700", green: "bg-emerald-50 text-emerald-800", amber: "bg-amber-50 text-amber-800", blue: "bg-sky-50 text-sky-800" }; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", styles[tone])}>{children}</span>; }
export function Field({ label, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: string; error?: string }) { return <label className="grid gap-1.5 text-sm font-semibold text-slate-800"><span>{label}</span><input className={cn("min-h-11 rounded-lg border bg-white px-3 font-normal outline-none transition focus:border-sky-700 focus:ring-2 focus:ring-sky-100", error ? "border-red-500" : "border-slate-300")} aria-invalid={!!error} {...props}/>{error && <span className="text-xs font-normal text-red-700">{error}</span>}</label>; }
export function Sheet({ open, onOpenChange, title, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; children: ReactNode }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-slate-950/35 data-[state=open]:animate-in"/><Dialog.Content className="fixed inset-y-0 right-0 z-50 w-full max-w-xl overflow-y-auto border-l border-slate-200 bg-white p-6 shadow-2xl focus:outline-none"><div className="flex items-start justify-between gap-4"><Dialog.Title className="font-heading text-xl font-semibold text-slate-950">{title}</Dialog.Title><Dialog.Close asChild><Button variant="ghost" aria-label="Close panel"><X size={20}/></Button></Dialog.Close></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
